# 2.1 张量数据结构

## 常量 tf.constant

In [13]:
import numpy as np
import tensorflow as tf

In [14]:
i = tf.constant(1)  # tf.int32
l = tf.constant(1, dtype=tf.int64)  # tf.int64
f = tf.constant(1.23)
d = tf.constant(1.23, dtype=tf.double)  # tf.double  float64
e = tf.constant(1.23, dtype=tf.float32)  # tf.float32
s = tf.constant('hello, world!')  # tf.string
b = tf.constant(True) #tf.bool类型常量
print(i)
print(l)
print(f)
print(d)
print(e)
print(s)
print(b)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1.23, shape=(), dtype=float32)
tf.Tensor(1.23, shape=(), dtype=float64)
tf.Tensor(1.23, shape=(), dtype=float32)
tf.Tensor(b'hello, world!', shape=(), dtype=string)
tf.Tensor(True, shape=(), dtype=bool)


In [15]:
print(tf.int64 == np.int64) 
print(tf.bool == np.bool)
print(tf.double == np.float64)
print(tf.string == np.unicode) # tf.string类型和np.unicode类型不等价

True
True
True
False


In [16]:
scalar = tf.constant(True)
print(tf.rank(scalar))

tf.Tensor(0, shape=(), dtype=int32)


In [20]:
print(scalar.numpy().ndim)

0


In [21]:
vector = tf.constant([1.0, 2.0, 3.0], dtype=tf.float32)
print(tf.rank(vector))

tf.Tensor(1, shape=(), dtype=int32)


In [22]:
mat = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], dtype=tf.float32)
print(tf.rank(mat))

tf.Tensor(2, shape=(), dtype=int32)


In [23]:
print(mat.numpy().ndim)

2


In [25]:
tensor3 = tf.constant([[[1,2,3], [1,2,3]], [[1, 2,3], [4,5,6]]])
print(tf.rank(tensor3))

tf.Tensor(3, shape=(), dtype=int32)


In [26]:
print(tensor3.numpy().ndim)

3


In [27]:
tensor4 = tf.constant([[[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]], [[[1,2,3], [1,2,3]], [[1,2,3],[1,3,4]]]])
print(tf.rank(tensor4))

tf.Tensor(4, shape=(), dtype=int32)


In [28]:
print(tensor4)

tf.Tensor(
[[[[1 2 3]
   [1 2 3]]

  [[1 2 3]
   [1 2 3]]]


 [[[1 2 3]
   [1 2 3]]

  [[1 2 3]
   [1 3 4]]]], shape=(2, 2, 2, 3), dtype=int32)


In [29]:
h = tf.constant([123,456],dtype = tf.int32)

In [33]:
f = tf.cast(h, tf.float32)

In [34]:
print(h.dtype, f.dtype)

<dtype: 'int32'> <dtype: 'float32'>


In [45]:
y = tf.constant([[1,2,3], [2,3,4]])
print(y.numpy())

[[1 2 3]
 [2 3 4]]


In [46]:
y = y.numpy()
y.shape

(2, 3)

In [47]:
u = tf.constant(u"你好 世界")

In [48]:
print(u.numpy())  

b'\xe4\xbd\xa0\xe5\xa5\xbd \xe4\xb8\x96\xe7\x95\x8c'


In [49]:
print(u.numpy().decode("utf-8"))

你好 世界


## 变量 tf.Variable

In [50]:
c = tf.constant([1.0,2.0])
print(c)

tf.Tensor([1. 2.], shape=(2,), dtype=float32)


In [51]:
print(id(c))

5383094848


In [52]:
c = c + tf.constant([2.0, 3.0])
print(c)

tf.Tensor([3. 5.], shape=(2,), dtype=float32)


In [53]:
print(id(c))

5382723120


#### 常量值不可以改变，常量的重新赋值相当于创造新的内存空

In [58]:
v = tf.Variable([1,2,3], name='v')
print(v)

<tf.Variable 'v:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>


In [59]:
print(id(v))

5055210944


In [61]:
v.assign_add([1,1, 1])
print(v)

<tf.Variable 'v:0' shape=(3,) dtype=int32, numpy=array([2, 3, 4], dtype=int32)>


In [62]:
print(id(v))   # 地址不变

5055210944


In [63]:
# 如果是赋值的话是会发生变化的
v = v + tf.constant([1,2,3])
print(v)
print(id(v))

tf.Tensor([3 5 7], shape=(3,), dtype=int32)
5053533712
